name: price_monitoring
version: 1.0.0
config-version: 2

profile: price_monitoring

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  price_monitoring:
    staging:
      +materialized: view
    marts:
      +materialized: table
